spring:
  profiles: local
  datasource:   
     url: jdbc:mariadb://localhost:3306/practise
     username: root
     password: root
     driver-class-name: org.mariadb.jdbc.Driver
     continue-on-error: true
     tomcat:   
       test-on-borrow: true    
       validation-query: SELECT 1    
       initial-size: 10    
       test-while-idle: true   
       time-between-eviction-runs-millis: 5000   
       min-evictable-idle-time-millis: 5000    
       min-idle: 0
  jpa:    
     show-sql: true
